// Country list with English + Arabic names.
export const countries = [
  { code: 'AF', en: 'Afghanistan', ar: 'أفغانستان' },
  { code: 'AL', en: 'Albania', ar: 'ألبانيا' },
  { code: 'DZ', en: 'Algeria', ar: 'الجزائر' },
  { code: 'AD', en: 'Andorra', ar: 'أندورا' },
  { code: 'AO', en: 'Angola', ar: 'أنغولا' },
  { code: 'AR', en: 'Argentina', ar: 'الأرجنتين' },
  { code: 'AM', en: 'Armenia', ar: 'أرمينيا' },
  { code: 'AU', en: 'Australia', ar: 'أستراليا' },
  { code: 'AT', en: 'Austria', ar: 'النمسا' },
  { code: 'AZ', en: 'Azerbaijan', ar: 'أذربيجان' },
  { code: 'BH', en: 'Bahrain', ar: 'البحرين' },
  { code: 'BD', en: 'Bangladesh', ar: 'بنغلاديش' },
  { code: 'BB', en: 'Barbados', ar: 'باربادوس' },
  { code: 'BY', en: 'Belarus', ar: 'بيلاروسيا' },
  { code: 'BE', en: 'Belgium', ar: 'بلجيكا' },
  { code: 'BZ', en: 'Belize', ar: 'بليز' },
  { code: 'BJ', en: 'Benin', ar: 'بنين' },
  { code: 'BT', en: 'Bhutan', ar: 'بوتان' },
  { code: 'BO', en: 'Bolivia', ar: 'بوليفيا' },
  { code: 'BA', en: 'Bosnia and Herzegovina', ar: 'البوسنة والهرسك' },
  { code: 'BW', en: 'Botswana', ar: 'بوتسوانا' },
  { code: 'BR', en: 'Brazil', ar: 'البرازيل' },
  { code: 'BN', en: 'Brunei', ar: 'بروناي' },
  { code: 'BG', en: 'Bulgaria', ar: 'بلغاريا' },
  { code: 'BF', en: 'Burkina Faso', ar: 'بوركينا فاسو' },
  { code: 'BI', en: 'Burundi', ar: 'بوروندي' },
  { code: 'KH', en: 'Cambodia', ar: 'كمبوديا' },
  { code: 'CM', en: 'Cameroon', ar: 'الكاميرون' },
  { code: 'CA', en: 'Canada', ar: 'كندا' },
  { code: 'CV', en: 'Cape Verde', ar: 'الرأس الأخضر' },
  { code: 'CF', en: 'Central African Republic', ar: 'أفريقيا الوسطى' },
  { code: 'TD', en: 'Chad', ar: 'تشاد' },
  { code: 'CL', en: 'Chile', ar: 'تشيلي' },
  { code: 'CN', en: 'China', ar: 'الصين' },
  { code: 'CO', en: 'Colombia', ar: 'كولومبيا' },
  { code: 'KM', en: 'Comoros', ar: 'جزر القمر' },
  { code: 'CG', en: 'Congo', ar: 'الكونغو' },
  { code: 'CD', en: 'Congo (DRC)', ar: 'الكونغو الديمقراطية' },
  { code: 'CR', en: 'Costa Rica', ar: 'كوستاريكا' },
  { code: 'CI', en: "Côte d'Ivoire", ar: 'ساحل العاج' },
  { code: 'HR', en: 'Croatia', ar: 'كرواتيا' },
  { code: 'CU', en: 'Cuba', ar: 'كوبا' },
  { code: 'CY', en: 'Cyprus', ar: 'قبرص' },
  { code: 'CZ', en: 'Czechia', ar: 'التشيك' },
  { code: 'DK', en: 'Denmark', ar: 'الدنمارك' },
  { code: 'DJ', en: 'Djibouti', ar: 'جيبوتي' },
  { code: 'DO', en: 'Dominican Republic', ar: 'الدومينيكان' },
  { code: 'EC', en: 'Ecuador', ar: 'الإكوادور' },
  { code: 'EG', en: 'Egypt', ar: 'مصر' },
  { code: 'SV', en: 'El Salvador', ar: 'السلفادور' },
  { code: 'GQ', en: 'Equatorial Guinea', ar: 'غينيا الاستوائية' },
  { code: 'ER', en: 'Eritrea', ar: 'إريتريا' },
  { code: 'EE', en: 'Estonia', ar: 'إستونيا' },
  { code: 'SZ', en: 'Eswatini', ar: 'إسواتيني' },
  { code: 'ET', en: 'Ethiopia', ar: 'إثيوبيا' },
  { code: 'FJ', en: 'Fiji', ar: 'فيجي' },
  { code: 'FI', en: 'Finland', ar: 'فنلندا' },
  { code: 'FR', en: 'France', ar: 'فرنسا' },
  { code: 'GA', en: 'Gabon', ar: 'الغابون' },
  { code: 'GM', en: 'Gambia', ar: 'غامبيا' },
  { code: 'GE', en: 'Georgia', ar: 'جورجيا' },
  { code: 'DE', en: 'Germany', ar: 'ألمانيا' },
  { code: 'GH', en: 'Ghana', ar: 'غانا' },
  { code: 'GR', en: 'Greece', ar: 'اليونان' },
  { code: 'GD', en: 'Grenada', ar: 'غرينادا' },
  { code: 'GT', en: 'Guatemala', ar: 'غواتيمالا' },
  { code: 'GN', en: 'Guinea', ar: 'غينيا' },
  { code: 'GW', en: 'Guinea-Bissau', ar: 'غينيا بيساو' },
  { code: 'GY', en: 'Guyana', ar: 'غيانا' },
  { code: 'HT', en: 'Haiti', ar: 'هايتي' },
  { code: 'HN', en: 'Honduras', ar: 'هندوراس' },
  { code: 'HK', en: 'Hong Kong', ar: 'هونغ كونغ' },
  { code: 'HU', en: 'Hungary', ar: 'المجر' },
  { code: 'IS', en: 'Iceland', ar: 'آيسلندا' },
  { code: 'IN', en: 'India', ar: 'الهند' },
  { code: 'ID', en: 'Indonesia', ar: 'إندونيسيا' },
  { code: 'IR', en: 'Iran', ar: 'إيران' },
  { code: 'IQ', en: 'Iraq', ar: 'العراق' },
  { code: 'IE', en: 'Ireland', ar: 'أيرلندا' },
  { code: 'IL', en: 'Israel', ar: 'إسرائيل' },
  { code: 'IT', en: 'Italy', ar: 'إيطاليا' },
  { code: 'JM', en: 'Jamaica', ar: 'جامايكا' },
  { code: 'JP', en: 'Japan', ar: 'اليابان' },
  { code: 'JO', en: 'Jordan', ar: 'الأردن' },
  { code: 'KZ', en: 'Kazakhstan', ar: 'كازاخستان' },
  { code: 'KE', en: 'Kenya', ar: 'كينيا' },
  { code: 'KI', en: 'Kiribati', ar: 'كيريباتي' },
  { code: 'KP', en: 'North Korea', ar: 'كوريا الشمالية' },
  { code: 'KR', en: 'South Korea', ar: 'كوريا الجنوبية' },
  { code: 'KW', en: 'Kuwait', ar: 'الكويت' },
  { code: 'KG', en: 'Kyrgyzstan', ar: 'قيرغيزستان' },
  { code: 'LA', en: 'Laos', ar: 'لاوس' },
  { code: 'LV', en: 'Latvia', ar: 'لاتفيا' },
  { code: 'LB', en: 'Lebanon', ar: 'لبنان' },
  { code: 'LS', en: 'Lesotho', ar: 'ليسوتو' },
  { code: 'LR', en: 'Liberia', ar: 'ليبيريا' },
  { code: 'LY', en: 'Libya', ar: 'ليبيا' },
  { code: 'LI', en: 'Liechtenstein', ar: 'ليختنشتاين' },
  { code: 'LT', en: 'Lithuania', ar: 'ليتوانيا' },
  { code: 'LU', en: 'Luxembourg', ar: 'لوكسمبورغ' },
  { code: 'MO', en: 'Macao', ar: 'ماكاو' },
  { code: 'MG', en: 'Madagascar', ar: 'مدغشقر' },
  { code: 'MW', en: 'Malawi', ar: 'مالاوي' },
  { code: 'MY', en: 'Malaysia', ar: 'ماليزيا' },
  { code: 'MV', en: 'Maldives', ar: 'جزر المالديف' },
  { code: 'ML', en: 'Mali', ar: 'مالي' },
  { code: 'MT', en: 'Malta', ar: 'مالطا' },
  { code: 'MR', en: 'Mauritania', ar: 'موريتانيا' },
  { code: 'MU', en: 'Mauritius', ar: 'موريشيوس' },
  { code: 'MX', en: 'Mexico', ar: 'المكسيك' },
  { code: 'MD', en: 'Moldova', ar: 'مولدوفا' },
  { code: 'MC', en: 'Monaco', ar: 'موناكو' },
  { code: 'MN', en: 'Mongolia', ar: 'منغوليا' },
  { code: 'ME', en: 'Montenegro', ar: 'الجبل الأسود' },
  { code: 'MA', en: 'Morocco', ar: 'المغرب' },
  { code: 'MZ', en: 'Mozambique', ar: 'موزمبيق' },
  { code: 'MM', en: 'Myanmar', ar: 'ميانمار' },
  { code: 'NA', en: 'Namibia', ar: 'ناميبيا' },
  { code: 'NP', en: 'Nepal', ar: 'نيبال' },
  { code: 'NL', en: 'Netherlands', ar: 'هولندا' },
  { code: 'NZ', en: 'New Zealand', ar: 'نيوزيلندا' },
  { code: 'NI', en: 'Nicaragua', ar: 'نيكاراغوا' },
  { code: 'NE', en: 'Niger', ar: 'النيجر' },
  { code: 'NG', en: 'Nigeria', ar: 'نيجيريا' },
  { code: 'MK', en: 'North Macedonia', ar: 'شمال مقدونيا' },
  { code: 'NO', en: 'Norway', ar: 'النرويج' },
  { code: 'OM', en: 'Oman', ar: 'عُمان' },
  { code: 'PK', en: 'Pakistan', ar: 'باكستان' },
  { code: 'PS', en: 'Palestine', ar: 'فلسطين' },
  { code: 'PA', en: 'Panama', ar: 'بنما' },
  { code: 'PG', en: 'Papua New Guinea', ar: 'بابوا غينيا الجديدة' },
  { code: 'PY', en: 'Paraguay', ar: 'باراغواي' },
  { code: 'PE', en: 'Peru', ar: 'البيرو' },
  { code: 'PH', en: 'Philippines', ar: 'الفلبين' },
  { code: 'PL', en: 'Poland', ar: 'بولندا' },
  { code: 'PT', en: 'Portugal', ar: 'البرتغال' },
  { code: 'QA', en: 'Qatar', ar: 'قطر' },
  { code: 'RO', en: 'Romania', ar: 'رومانيا' },
  { code: 'RU', en: 'Russia', ar: 'روسيا' },
  { code: 'RW', en: 'Rwanda', ar: 'رواندا' },
  { code: 'SA', en: 'Saudi Arabia', ar: 'السعودية' },
  { code: 'SN', en: 'Senegal', ar: 'السنغال' },
  { code: 'RS', en: 'Serbia', ar: 'صربيا' },
  { code: 'SC', en: 'Seychelles', ar: 'سيشل' },
  { code: 'SL', en: 'Sierra Leone', ar: 'سيراليون' },
  { code: 'SG', en: 'Singapore', ar: 'سنغافورة' },
  { code: 'SK', en: 'Slovakia', ar: 'سلوفاكيا' },
  { code: 'SI', en: 'Slovenia', ar: 'سلوفينيا' },
  { code: 'SO', en: 'Somalia', ar: 'الصومال' },
  { code: 'ZA', en: 'South Africa', ar: 'جنوب أفريقيا' },
  { code: 'SS', en: 'South Sudan', ar: 'جنوب السودان' },
  { code: 'ES', en: 'Spain', ar: 'إسبانيا' },
  { code: 'LK', en: 'Sri Lanka', ar: 'سريلانكا' },
  { code: 'SD', en: 'Sudan', ar: 'السودان' },
  { code: 'SR', en: 'Suriname', ar: 'سورينام' },
  { code: 'SE', en: 'Sweden', ar: 'السويد' },
  { code: 'CH', en: 'Switzerland', ar: 'سويسرا' },
  { code: 'SY', en: 'Syria', ar: 'سوريا' },
  { code: 'TW', en: 'Taiwan', ar: 'تايوان' },
  { code: 'TJ', en: 'Tajikistan', ar: 'طاجيكستان' },
  { code: 'TZ', en: 'Tanzania', ar: 'تنزانيا' },
  { code: 'TH', en: 'Thailand', ar: 'تايلاند' },
  { code: 'TL', en: 'Timor-Leste', ar: 'تيمور الشرقية' },
  { code: 'TG', en: 'Togo', ar: 'توغو' },
  { code: 'TT', en: 'Trinidad and Tobago', ar: 'ترينيداد وتوباغو' },
  { code: 'TN', en: 'Tunisia', ar: 'تونس' },
  { code: 'TR', en: 'Turkey', ar: 'تركيا' },
  { code: 'TM', en: 'Turkmenistan', ar: 'تركمانستان' },
  { code: 'UG', en: 'Uganda', ar: 'أوغندا' },
  { code: 'UA', en: 'Ukraine', ar: 'أوكرانيا' },
  { code: 'AE', en: 'United Arab Emirates', ar: 'الإمارات' },
  { code: 'GB', en: 'United Kingdom', ar: 'المملكة المتحدة' },
  { code: 'US', en: 'United States', ar: 'الولايات المتحدة' },
  { code: 'UY', en: 'Uruguay', ar: 'الأوروغواي' },
  { code: 'UZ', en: 'Uzbekistan', ar: 'أوزبكستان' },
  { code: 'VU', en: 'Vanuatu', ar: 'فانواتو' },
  { code: 'VA', en: 'Vatican City', ar: 'الفاتيكان' },
  { code: 'VE', en: 'Venezuela', ar: 'فنزويلا' },
  { code: 'VN', en: 'Vietnam', ar: 'فيتنام' },
  { code: 'YE', en: 'Yemen', ar: 'اليمن' },
  { code: 'ZM', en: 'Zambia', ar: 'زامبيا' },
  { code: 'ZW', en: 'Zimbabwe', ar: 'زيمبابوي' },
];

export const countryName = (code, lang) => {
  const c = countries.find((x) => x.code === code || x.en === code);
  if (!c) return code || '';
  return lang === 'ar' ? c.ar : c.en;
};
